-- Append-only evidence of legal-document acceptance captured during registration.
-- Apply before deploying the matching server release.

CREATE TABLE IF NOT EXISTS public.user_consents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  terms_version text NOT NULL CHECK (terms_version ~ '^\d{4}-\d{2}-\d{2}$'),
  terms_accepted_at timestamptz NOT NULL,
  privacy_version text NOT NULL CHECK (privacy_version ~ '^\d{4}-\d{2}-\d{2}$'),
  privacy_acknowledged_at timestamptz NOT NULL,
  source text NOT NULL DEFAULT 'registration' CHECK (char_length(source) BETWEEN 1 AND 50),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, terms_version, privacy_version)
);

CREATE INDEX IF NOT EXISTS idx_user_consents_user_created
  ON public.user_consents (user_id, created_at DESC);

ALTER TABLE public.user_consents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No direct access to user_consents" ON public.user_consents;
CREATE POLICY "No direct access to user_consents"
  ON public.user_consents FOR ALL USING (false) WITH CHECK (false);

REVOKE ALL ON TABLE public.user_consents FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.user_consents_id_seq FROM anon, authenticated;

GRANT SELECT, INSERT ON TABLE public.user_consents TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.user_consents_id_seq TO service_role;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE public.user_consents FROM service_role;
