-- ============================================
-- Core tables: users, subscriptions, profiles, readings, newsletter_subscribers
-- These tables are referenced throughout the codebase but had no migration.
-- ============================================

-- Users table (synced from auth.users via JIT repair in auth.js)
create table if not exists users (
  id uuid references auth.users primary key,
  email text not null,
  role text default 'user',
  first_name text,
  birth_date text,
  birth_time text,
  birth_place text,
  is_premium boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table users enable row level security;

create policy "Users can view their own profile"
on users for select
using ( auth.uid() = id );

create policy "Users can update their own profile"
on users for update
using ( auth.uid() = id );

-- Subscriptions table
create table if not exists subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  plan_type text not null default 'free',
  status text default 'active',
  credits integer default 0,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table subscriptions enable row level security;

create policy "Users can view their own subscription"
on subscriptions for select
using ( auth.uid() = user_id );

-- Profiles table (used by mentor for context)
create table if not exists profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  name text,
  birth_date text,
  zodiac_sign text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Users can view their own profile data"
on profiles for select
using ( auth.uid() = user_id );

create policy "Users can update their own profile data"
on profiles for update
using ( auth.uid() = user_id );

-- Readings table (tarot, crystal-ball, horoscope, numerology, etc.)
create table if not exists readings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null,
  data jsonb not null default '{}',
  is_favorite boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table readings enable row level security;

create policy "Users can view their own readings"
on readings for select
using ( auth.uid() = user_id );

create policy "Users can insert their own readings"
on readings for insert
with check ( auth.uid() = user_id );

create policy "Users can update their own readings"
on readings for update
using ( auth.uid() = user_id );

create policy "Users can delete their own readings"
on readings for delete
using ( auth.uid() = user_id );

-- Newsletter subscribers
create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text default 'web_footer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table newsletter_subscribers enable row level security;

-- Cache: Horoscopes
create table if not exists cache_horoscopes (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  sign text,
  period text,
  response text,
  period_label text,
  generated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Cache: Numerology
create table if not exists cache_numerology (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  name text,
  birth_date text,
  birth_time text,
  life_path integer,
  destiny integer,
  soul integer,
  personality integer,
  response text,
  generated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ============================================
-- Performance indexes for frequently queried fields
-- ============================================
create index if not exists idx_readings_user_created on readings(user_id, created_at desc);
create index if not exists idx_subscriptions_user on subscriptions(user_id);
create index if not exists idx_mentor_messages_user_created on mentor_messages(user_id, created_at);
create index if not exists idx_newsletter_email on newsletter_subscribers(email);
create index if not exists idx_cache_horoscopes_key on cache_horoscopes(cache_key);
create index if not exists idx_cache_numerology_key on cache_numerology(cache_key);
